# Generated by Django 4.1.4 on 2023-05-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0073_retainerinvoices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RetainerInvoices',
        ),
    ]
