# Generated by Django 4.1.4 on 2023-05-22 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0075_retainerinvoices1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RetainerInvoices1',
            new_name='RetainerInvoices',
        ),
    ]
