# Generated by Django 4.1.4 on 2023-05-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0076_rename_retainerinvoices1_retainerinvoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retainerinvoices',
            name='invoice_number',
            field=models.IntegerField(null=True),
        ),
    ]
