# Generated by Django 4.1 on 2023-05-29 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0081_retainerinvoices_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='recurring_expense',
            fields=[
                ('recur_expenseid', models.AutoField(primary_key=True, serialize=False, verbose_name='eid')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expenseaccount', models.CharField(blank=True, max_length=100, null=True)),
                ('expensetype', models.CharField(blank=True, max_length=100, null=True)),
                ('hsn', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('paidthrough', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_treat', models.CharField(blank=True, max_length=100, null=True)),
                ('destinofsupply', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('rev_charge', models.CharField(blank=True, max_length=50, null=True)),
                ('tax', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
