# Generated by Django 4.1 on 2023-05-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0084_recurring_expense_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
