# Generated by Django 4.1 on 2023-05-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0085_alter_vendor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_expense',
            name='gstin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
