# Generated by Django 4.2.2 on 2023-07-18 08:04

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0087_alter_customer_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('swift_code', models.CharField(max_length=11)),
                ('bank_name', models.CharField(choices=[('SBI', 'State Bank of India'), ('BOB', 'Bank of Baroda'), ('BOI', 'Bank of India'), ('BOM', 'Bank of Maharashtra'), ('CAN', 'Canara Bank'), ('CBI', 'Central Bank of India'), ('IND', 'Indian Bank'), ('IOB', 'Indian Overseas Bank'), ('PSB', 'Punjab & Sind Bank'), ('PNB', 'Punjab National Bank'), ('UCO', 'UCO Bank'), ('UBI', 'Union Bank of India'), ('AXIS', 'Axis Bank Ltd.'), ('BANDHAN', 'Bandhan Bank Ltd.'), ('CSB', 'CSB Bank Limited'), ('CUB', 'City Union Bank Ltd.'), ('DCB', 'DCB Bank Ltd.'), ('DHANLAXMI', 'Dhanlaxmi Bank Ltd.'), ('FEDERAL', 'Federal Bank Ltd.'), ('HDFC', 'HDFC Bank Ltd.'), ('ICICI', 'ICICI Bank Ltd.')], max_length=10)),
                ('branch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('CC', 'Credit Card'), ('BA', 'Bank Account')], default='BA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='BankConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_cheque_book_range', models.BooleanField(default=False)),
                ('enable_cheque_printing', models.BooleanField(default=False)),
                ('set_cheque_printing_configuration', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BankingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_it_number', models.CharField(max_length=10)),
                ('registration_details', models.TextField()),
                ('gstin_un', models.CharField(max_length=15)),
                ('set_alter_gst_details', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MailingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(choices=[('AN', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CH', 'Chhattisgarh'), ('DL', 'National Capital Territory of Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('LA', 'Ladakh'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UT', 'Uttarakhand'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal')], max_length=2)),
                ('pin', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='noninventory',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='noninventory',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='noninventory',
            name='expacnt',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='noninventory',
            name='incomeacnt',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='noninventory',
            name='initialqty',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='noninventory',
            name='invacnt',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='noninventory',
            name='purchaseinfo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='noninventory',
            name='purtax',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='noninventory',
            name='salesprice',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AddField(
            model_name='noninventory',
            name='stockalrt',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='service',
            name='check1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='check2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='balance_sheet',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
