# Generated by Django 4.2.2 on 2023-08-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0088_bankaccount_bankaccountholder_bankconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
