# Generated by Django 4.2.2 on 2023-08-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0089_bankaccount_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankingdetails',
            name='registration_details',
        ),
        migrations.AddField(
            model_name='bankingdetails',
            name='registration_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('composition', 'Composition'), ('consumer', 'Consumer'), ('unregistered', 'Unregistered'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
