# Generated by Django 4.2.2 on 2023-08-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0090_remove_bankingdetails_registration_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccountholder',
            old_name='name',
            new_name='bankname',
        ),
    ]
