# Generated by Django 4.2.2 on 2023-08-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0091_rename_name_bankaccountholder_bankname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccountholder',
            old_name='bankname',
            new_name='name',
        ),
    ]
