# Generated by Django 4.2.2 on 2023-08-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0092_rename_bankname_bankaccountholder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=15),
        ),
    ]
