# Generated by Django 4.2.2 on 2023-08-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0093_alter_bankaccount_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountholder',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='bankaccountholder',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
